language: node_js
node_js:
  - "0.11"
  - "0.10"
branches:
  only:
    - master
before_install:
  - npm install npm -g
before_script:
  - npm install
  - npm install istanbul coveralls
script: npm run travis-test
